name: Daily Job Check

on:
  push:                # ⬅️ run on every push to main
    branches: ["main"]

  schedule:            # still run every day at 09:00 UTC
    - cron: "0 9 * * *"

  workflow_dispatch:   # keep the manual run button

jobs:
  run-jobchecker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Run the job bot
        run: go run main.go
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}